### ISSUE TITLE
Workplan

### ISSUE THREAD

**Issue by psychemedia** [OpenComputingLab/reusable-content-example#1]
This isn't the right repo for this issue. but it's the repo I'm woking in atm... so here goes.. On the to do list:

- [ ] rewrite the advocacy elements of this repo to say something like: a) lots of modules using Juoyter notebooks; b) no sensible route to PDF for print pack; c) how about map to OU-XML and genrate PDF that way; d) I wonder, can we author OU-XML content this way etc
- [ ] round tripping: set up a test repo to act as a testbed for deveoloping round tripping;
- [ ] simple round tripping works...
- [ ] more elaboarate round tripping works...
- [ ] do a demo of TM351 week to OU-XML PDF
- [ ] see if we can get this repo to round trip
- [ ] see if we can get TM351 week to round trip
- [ ] see if we can roundtrip my week of TM112
